org: ublavins
app: aws-serverless-python-starter
service: aws-serverless-python-starter

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9

functions:
  hello:
    handler: handler.hello
