org: ublavins
app: aws-serverless-python-starter
service: aws-serverless-python-starter

frameworkVersion: '3'

provider:
  # generic configuration of function and serverless project
  name: aws
  runtime: python3.9
  region: eu-west-2
  stage: dev
  # configure serverless deployment bucket
  deploymentBucket:
    name: aws-serverless-python-starter-${self:provider.region}
    blockPublicAccess: true
    versioning: true
    serverSideEncryption: AES256

functions:
  hello:
    handler: handler.hello

plugins:
  - serverless-python-requirements
